// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNFv0k3lI78TfBzTqHydhBCx6INtpBOT0',
    appId: '1:22477571679:web:4c7e21a425a5064ea97dea',
    messagingSenderId: '22477571679',
    projectId: 'playpal-5c3dc',
    authDomain: 'playpal-5c3dc.firebaseapp.com',
    storageBucket: 'playpal-5c3dc.appspot.com',
    measurementId: 'G-YS1FK70RSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOhBlkdN9Il63ppchLnMtbW8-Tjp_nUFU',
    appId: '1:22477571679:android:a8f30efaf0302bdda97dea',
    messagingSenderId: '22477571679',
    projectId: 'playpal-5c3dc',
    storageBucket: 'playpal-5c3dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhva76rUc4IjzgEFYjUtRmNWijLU0sEws',
    appId: '1:22477571679:ios:8ab8eb5173c92f82a97dea',
    messagingSenderId: '22477571679',
    projectId: 'playpal-5c3dc',
    storageBucket: 'playpal-5c3dc.appspot.com',
    iosBundleId: 'com.albertphamcs.playpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhva76rUc4IjzgEFYjUtRmNWijLU0sEws',
    appId: '1:22477571679:ios:64f7e505c6ae1835a97dea',
    messagingSenderId: '22477571679',
    projectId: 'playpal-5c3dc',
    storageBucket: 'playpal-5c3dc.appspot.com',
    iosBundleId: 'com.example.playpal.RunnerTests',
  );
}
