enum DogBreed {
  affenpinscher('Affenpinscher'),
  afghanhound('Afghan Hound'),
  africanis('Africanis'),
  aidi('Aidi'),
  airedaleterrier('Airedale Terrier'),
  akbash('Akbash'),
  akita('Akita'),
  aksaraymalaklisi('Aksaray Malaklisi'),
  alanoespanol('Alano Español'),
  alapahabluebloodbulldog('Alapaha Blue Blood Bulldog'),
  alaskankleekai('Alaskan Klee Kai'),
  alaskanmalamute('Alaskan Malamute'),
  alaskanhusky('Alaskan husky'),
  alopekis('Alopekis'),
  alpinedachsbracke('Alpine Dachsbracke'),
  americanbulldog('American Bulldog'),
  americanbully('American Bully'),
  americancockerspaniel('American Cocker Spaniel'),
  americanenglishcoonhound('American English Coonhound'),
  americaneskimodog('American Eskimo Dog'),
  americanfoxhound('American Foxhound'),
  americanhairlessterrier('American Hairless Terrier'),
  americanleopardhound('American Leopard Hound'),
  americanpitbullterrier('American Pit Bull Terrier'),
  americanstaffordshireterrier('American Staffordshire Terrier'),
  americanstaghound('American Staghound'),
  americanwaterspaniel('American Water Spaniel'),
  anglofrancaisdepetitevenerie('Anglo-Français de Petite Vénerie'),
  appenzellersennenhund('Appenzeller Sennenhund'),
  argentinepila('Argentine Pila'),
  ariegepointer('Ariège Pointer'),
  ariegeois('Ariégeois'),
  armant('Armant'),
  armeniangampr('Armenian Gampr'),
  artoishound('Artois Hound'),
  assyrianmastiff('Assyrian Mastiff'),
  australiancattledog('Australian Cattle Dog'),
  australiankelpie('Australian Kelpie'),
  australianshepherd('Australian Shepherd'),
  australiansilkyterrier('Australian Silky Terrier'),
  australianstumpytailcattledog('Australian Stumpy Tail Cattle Dog'),
  australianterrier('Australian Terrier'),
  austrianblackandtanhound('Austrian Black and Tan Hound'),
  austrianpinscher('Austrian Pinscher'),
  azawakh('Azawakh'),
  bakharwal('Bakharwal'),
  banjarahound('Banjara Hound'),
  bankhardog('Bankhar Dog'),
  barakhound('Barak hound'),
  barbadodaterceira('Barbado da Terceira'),
  barbet('Barbet'),
  basenji('Basenji'),
  basqueshepherddog('Basque Shepherd Dog'),
  bassetartesiennormand('Basset Artésien Normand'),
  bassetbleudegascogne('Basset Bleu de Gascogne'),
  bassetfauvedebretagne('Basset Fauve de Bretagne'),
  bassethound('Basset Hound'),
  bavarianmountainhound('Bavarian Mountain Hound'),
  beagle('Beagle'),
  beagleharrier('Beagle-Harrier'),
  beaglier('Beaglier'),
  beardedcollie('Bearded Collie'),
  beauceron('Beauceron'),
  bedlingtonterrier('Bedlington Terrier'),
  belgianshepherd('Belgian Shepherd'),
  bergamascoshepherd('Bergamasco Shepherd'),
  bergerpicard('Berger Picard'),
  bernesemountaindog('Bernese Mountain Dog'),
  bichonfrise('Bichon Frisé'),
  biewerterrier('Biewer Terrier'),
  billy('Billy'),
  blackmouthcur('Black Mouth Cur'),
  blacknorwegianelkhound('Black Norwegian Elkhound'),
  blackrussianterrier('Black Russian Terrier'),
  blackandtancoonhound('Black and Tan Coonhound'),
  blackandtanterrier('Black and Tan Terrier'),
  bloodhound('Bloodhound'),
  bluelacy('Blue Lacy'),
  bluepicardyspaniel('Blue Picardy Spaniel'),
  bluetickcoonhound('Bluetick Coonhound'),
  boerboel('Boerboel'),
  bohemianshepherd('Bohemian Shepherd'),
  bolognese('Bolognese'),
  borador('Borador'),
  bordercollie('Border Collie'),
  borderterrier('Border Terrier'),
  borzoi('Borzoi'),
  bostonterrier('Boston Terrier'),
  bouvierdesardennes('Bouvier des Ardennes'),
  bouvierdesflandres('Bouvier des Flandres'),
  boxer('Boxer'),
  boykinspaniel('Boykin Spaniel'),
  braccoitaliano('Bracco Italiano'),
  braquefrancais('Braque Français'),
  braquesaintgermain('Braque Saint-Germain'),
  braquedauvergne('Braque d\'Auvergne'),
  braquedubourbonnais('Braque du Bourbonnais'),
  brazilianterrier('Brazilian Terrier'),
  briard('Briard'),
  briquetgriffonvendeen('Briquet Griffon Vendéen'),
  briquetdeprovence('Briquet de Provence'),
  brittany('Brittany'),
  broholmer('Broholmer'),
  brunojurahound('Bruno Jura Hound'),
  bucovinashepherddog('Bucovina Shepherd Dog'),
  bulgarianhound('Bulgarian Hound'),
  bulgarianscenthound('Bulgarian Scenthound'),
  bullarab('Bull Arab'),
  bullterrier('Bull Terrier'),
  bulldog('Bulldog'),
  bullmastiff('Bullmastiff'),
  bullykutta('Bully Kutta'),
  burgospointer('Burgos Pointer'),
  bacha('Bắc Hà'),
  camemallorqui('Ca Mè Mallorquí'),
  caratermallorqui('Ca Rater Mallorquí'),
  cadebou('Ca de Bou'),
  cairnterrier('Cairn Terrier'),
  calupoh('Calupoh'),
  campeirobulldog('Campeiro Bulldog'),
  candechira('Can de Chira'),
  candepalleiro('Can de Palleiro'),
  canaandog('Canaan Dog'),
  canadianeskimodog('Canadian Eskimo Dog'),
  canecorso('Cane Corso'),
  caneparatore('Cane Paratore'),
  canedioropa('Cane di Oropa'),
  cantabrianwaterdog('Cantabrian Water Dog'),
  caodegadotransmontano('Cão de Gado Transmontano'),
  cardiganwelshcorgi('Cardigan Welsh Corgi'),
  carealeones('Carea Leonés'),
  carolinadog('Carolina Dog'),
  carpathianshepherddog('Carpathian Shepherd Dog'),
  castrolaboreirodog('Castro Laboreiro Dog'),
  catahoulaleoparddog('Catahoula Leopard Dog'),
  catalansheepdog('Catalan Sheepdog'),
  caucasianshepherddog('Caucasian Shepherd Dog'),
  cavachon('Cavachon'),
  cavalierkingcharlesspaniel('Cavalier King Charles Spaniel'),
  cavapoochon('Cavapoochon'),
  cavoodleorcavapoo('Cavoodle or Cavapoo'),
  centralasianshepherddog('Central Asian Shepherd Dog'),
  ceskyterrier('Cesky Terrier'),
  ceskyfousek('Český fousek'),
  ceskystrakatypes('Český strakatý pes'),
  chesapeakebayretriever('Chesapeake Bay Retriever'),
  chienfrancaisblancetnoir('Chien Français Blanc et Noir'),
  chienfrancaisblancetorange('Chien Français Blanc et Orange'),
  chienfrancaistricolore('Chien Français Tricolore'),
  chihuahua('Chihuahua'),
  chileanterrier('Chilean Terrier'),
  chinesecresteddog('Chinese Crested Dog'),
  chinook('Chinook'),
  chippiparai('Chippiparai'),
  chiweenie('Chiweenie'),
  chongqing('Chongqing'),
  chorkie('Chorkie'),
  chortai('Chortai'),
  chowchow('Chow Chow'),
  chug('Chug'),
  chukotkasleddog('Chukotka sled dog'),
  cimarronuruguayo('Cimarrón Uruguayo'),
  cirnecodelletna('Cirneco dell\'Etna'),
  clumberspaniel('Clumber Spaniel'),
  cockapoo('Cockapoo'),
  cojack('Cojack'),
  colombianfinohound('Colombian Fino Hound'),
  continentalbulldog('Continental bulldog'),
  corsicandog('Corsican Dog'),
  cotondetulear('Coton de Tulear'),
  cretanhound('Cretan Hound'),
  croatiansheepdog('Croatian Sheepdog'),
  curlycoatedretriever('Curly-coated Retriever'),
  czechoslovakianwolfdog('Czechoslovakian Wolfdog'),
  dachshund('Dachshund'),
  dalmatian('Dalmatian'),
  dandiedinmontterrier('Dandie Dinmont Terrier'),
  daniff('Daniff'),
  danishspitz('Danish Spitz'),
  danishswedishfarmdog('Danish–Swedish Farmdog'),
  denmarkfeist('Denmark Feist'),
  dikkulak('Dikkulak'),
  dingo('Dingo'),
  dobermann('Dobermann'),
  dogoargentino('Dogo Argentino'),
  dogosardesco('Dogo Sardesco'),
  doguebrasileiro('Dogue Brasileiro'),
  doguedebordeaux('Dogue de Bordeaux'),
  donggyeongi('Donggyeongi'),
  dorgi('Dorgi'),
  drentsepatrijshond('Drentse Patrijshond'),
  drever('Drever'),
  dunker('Dunker'),
  dutchshepherd('Dutch Shepherd'),
  dutchsmoushond('Dutch Smoushond'),
  easteuropeanshepherd('East European Shepherd'),
  eastsiberianlaika('East Siberian Laika'),
  ecuadorianhairlessdog('Ecuadorian Hairless Dog'),
  englishcockerspaniel('English Cocker Spaniel'),
  englishfoxhound('English Foxhound'),
  englishmastiff('English Mastiff'),
  englishsetter('English Setter'),
  englishshepherd('English Shepherd'),
  englishspringerspaniel('English Springer Spaniel'),
  englishtoyterrierblackandtan('English Toy Terrier (Black & Tan)'),
  entlebuchermountaindog('Entlebucher Mountain Dog'),
  erbitxakur('Erbi Txakur'),
  estonianhound('Estonian Hound'),
  estrelamountaindog('Estrela Mountain Dog'),
  eurasier('Eurasier'),
  eurohound('Eurohound'),
  faroesesheepdog('Faroese Sheepdog'),
  feist('Feist'),
  fieldspaniel('Field Spaniel'),
  filabrasileiro('Fila Brasileiro'),
  finnishhound('Finnish Hound'),
  finnishlapphund('Finnish Lapphund'),
  finnishspitz('Finnish Spitz'),
  flatcoatedretriever('Flat-coated Retriever'),
  frenchbulldog('French Bulldog'),
  frenchspaniel('French Spaniel'),
  galgoespanol('Galgo Español'),
  gasconsaintongeois('Gascon Saintongeois'),
  gauchosheepdog('Gaucho sheepdog'),
  georgianshepherd('Georgian Shepherd'),
  gerberianshepsky('Gerberian Shepsky'),
  germanhound('German Hound'),
  germanlonghairedpointer('German Longhaired Pointer'),
  germanpinscher('German Pinscher'),
  germanroughhairedpointer('German Roughhaired Pointer'),
  germanshepherd('German Shepherd'),
  germanshorthairedpointer('German Shorthaired Pointer'),
  germanspaniel('German Spaniel'),
  germanspitz('German Spitz'),
  germanwirehairedpointer('German Wirehaired Pointer'),
  giantschnauzer('Giant Schnauzer'),
  glenofimaalterrier('Glen of Imaal Terrier'),
  goldador('Goldador'),
  goldenretriever('Golden Retriever'),
  goldendoodle('Goldendoodle'),
  gordonsetter('Gordon Setter'),
  gonczypolski('Gończy Polski'),
  grandanglofrancaisblancetnoir('Grand Anglo-Français Blanc et Noir'),
  grandanglofrancaisblancetorange('Grand Anglo-Français Blanc et Orange'),
  grandanglofrancaistricolore('Grand Anglo-Français Tricolore'),
  grandbassetgriffonvendeen('Grand Basset Griffon Vendéen'),
  grandbleudegascogne('Grand Bleu de Gascogne'),
  grandgriffonvendeen('Grand Griffon Vendéen'),
  greatdane('Great Dane'),
  greaterswissmountaindog('Greater Swiss Mountain Dog'),
  greekharehound('Greek Harehound'),
  greekshepherd('Greek Shepherd'),
  greenlanddog('Greenland Dog'),
  greyhound('Greyhound'),
  greyster('Greyster'),
  griffonbleudegascogne('Griffon Bleu de Gascogne'),
  griffonbruxellois('Griffon Bruxellois'),
  griffonfauvedebretagne('Griffon Fauve de Bretagne'),
  griffonnivernais('Griffon Nivernais'),
  guatemalandogo('Guatemalan Dogo'),
  gulldong('Gull Dong'),
  gullterrier('Gull Terrier'),
  haldenhound('Halden Hound'),
  halleforselkhound('Hällefors Elkhound'),
  hamiltonstovare('Hamiltonstövare'),
  hanoverhound('Hanover Hound'),
  harrier('Harrier'),
  havanese('Havanese'),
  himalayansheepdog('Himalayan Sheepdog'),
  hmongbobtaildog('Hmong bobtail dog'),
  hokkaido('Hokkaido'),
  hovawart('Hovawart'),
  huntaway('Huntaway'),
  hygenhound('Hygen Hound'),
  ibizanhound('Ibizan Hound'),
  icelandicsheepdog('Icelandic Sheepdog'),
  indianspitz('Indian Spitz'),
  indianpariahdog('Indian pariah dog'),
  irishredandwhitesetter('Irish Red and White Setter'),
  irishsetter('Irish Setter'),
  irishterrier('Irish Terrier'),
  irishwaterspaniel('Irish Water Spaniel'),
  irishwolfhound('Irish Wolfhound'),
  istriancoarsehairedhound('Istrian Coarse-haired Hound'),
  istrianshorthairedhound('Istrian Shorthaired Hound'),
  italiangreyhound('Italian Greyhound'),
  jackrussellterrier('Jack Russell Terrier'),
  jacktzu('Jack Tzu'),
  jackabee('Jackabee'),
  jagdterrier('Jagdterrier'),
  jamthund('Jämthund'),
  japanesechin('Japanese Chin'),
  japanesespitz('Japanese Spitz'),
  japaneseterrier('Japanese Terrier'),
  jeju('Jeju'),
  jonangi('Jonangi'),
  jug('Jug'),
  kaiken('Kai Ken'),
  kaikadi('Kaikadi'),
  kamchatkasleddog('Kamchatka Sled Dog'),
  kangalshepherddog('Kangal Shepherd Dog'),
  kangaroodog('Kangaroo dog'),
  kanni('Kanni'),
  karakachan('Karakachan'),
  karelianbeardog('Karelian Bear Dog'),
  karelofinnishlaika('Karelo-Finnish Laika'),
  kars('Kars'),
  karstshepherd('Karst Shepherd'),
  keeshond('Keeshond'),
  kerrybeagle('Kerry Beagle'),
  kerryblueterrier('Kerry Blue Terrier'),
  khala('Khala'),
  kingcharlesspaniel('King Charles Spaniel'),
  kingshepherd('King Shepherd'),
  kintamani('Kintamani'),
  kishu('Kishu'),
  kokoni('Kokoni'),
  kombai('Kombai'),
  komondor('Komondor'),
  kooikerhondje('Kooikerhondje'),
  koolie('Koolie'),
  koreanjindo('Korean Jindo'),
  kromfohrlander('Kromfohrländer'),
  kuchi('Kuchi'),
  kunming('Kunming'),
  kurdishmastiff('Kurdish Mastiff'),
  kuvasz('Kuvasz'),
  labradoodle('Labradoodle'),
  labradorretriever('Labrador Retriever'),
  lagottoromagnolo('Lagotto Romagnolo'),
  lai('Lài'),
  lakelandterrier('Lakeland Terrier'),
  lancashireheeler('Lancashire Heeler'),
  landseer('Landseer'),
  lapponianherder('Lapponian Herder'),
  largemunsterlander('Large Münsterländer'),
  leonberger('Leonberger'),
  levrierosardo('Levriero Sardo'),
  lhasaapso('Lhasa Apso'),
  liangshandog('Liangshan Dog'),
  lithuanianhound('Lithuanian Hound'),
  lobitoherreno('Lobito Herreño'),
  longdog('Longdog'),
  lowchen('Löwchen'),
  lucasterrier('Lucas Terrier'),
  lupoitaliano('Lupo Italiano'),
  lurcher('Lurcher'),
  mackenzieriverhusky('Mackenzie River husky'),
  magyaragar('Magyar Agár'),
  mahrattahound('Mahratta Hound'),
  majorcashepherddog('Majorca Shepherd Dog'),
  malshi('Mal-shi'),
  maltese('Maltese'),
  maltipoo('Maltipoo'),
  manchesterterrier('Manchester Terrier'),
  maneto('Maneto'),
  maremmanoabruzzesesheepdog('Maremmano-Abruzzese Sheepdog'),
  markiesje('Markiesje'),
  mcnab('McNab'),
  miniatureamericanshepherd('Miniature American Shepherd'),
  miniaturebullterrier('Miniature Bull Terrier'),
  miniaturefoxterrier('Miniature Fox Terrier'),
  miniaturepinscher('Miniature Pinscher'),
  miniatureschnauzer('Miniature Schnauzer'),
  molossusofepirus('Molossus of Epirus'),
  mongrel('Mongrel'),
  montenegrinmountainhound('Montenegrin Mountain Hound'),
  moscowwatchdog('Moscow Watchdog'),
  mountaincur('Mountain Cur'),
  mountainfeist('Mountain Feist'),
  mudholhound('Mudhol Hound'),
  mudi('Mudi'),
  mutt('Mutt'),
  neapolitanmastiff('Neapolitan Mastiff'),
  nenetsherdinglaika('Nenets Herding Laika'),
  newguineasingingdog('New Guinea singing dog'),
  newzealandheadingdog('New Zealand Heading Dog'),
  newfoundland('Newfoundland'),
  norfolkterrier('Norfolk Terrier'),
  norrbottenspets('Norrbottenspets'),
  northerninuitdog('Northern Inuit Dog'),
  norwegianbuhund('Norwegian Buhund'),
  norwegianelkhound('Norwegian Elkhound'),
  norwegianlundehund('Norwegian Lundehund'),
  norwichterrier('Norwich Terrier'),
  novascotiaducktollingretriever('Nova Scotia Duck Tolling Retriever'),
  olddanishpointer('Old Danish Pointer'),
  oldenglishsheepdog('Old English Sheepdog'),
  oldeenglishbulldogge('Olde English Bulldogge'),
  otterhound('Otterhound'),
  pachonnavarro('Pachón Navarro'),
  pampasdeerhound('Pampas Deerhound'),
  papillon('Papillon'),
  parsonrussellterrier('Parson Russell Terrier'),
  pastorgarafiano('Pastor Garafiano'),
  pastoredellalessiniaedellagorai('Pastore della Lessinia e del Lagorai'),
  patagoniansheepdog('Patagonian Sheepdog'),
  patterdaleterrier('Patterdale Terrier'),
  peekapoo('Peekapoo'),
  pekingese('Pekingese'),
  pembrokewelshcorgi('Pembroke Welsh Corgi'),
  perdigueirogalego('Perdigueiro Galego'),
  perromajorero('Perro Majorero'),
  peruvianhairlessdog('Peruvian Hairless Dog'),
  petitbassetgriffonvendeen('Petit Basset Griffon Vendéen'),
  petitbleudegascogne('Petit Bleu de Gascogne'),
  phalene('Phalène'),
  pharaohhound('Pharaoh Hound'),
  phuquocridgeback('Phu Quoc Ridgeback'),
  picardyspaniel('Picardy Spaniel'),
  plotthound('Plott Hound'),
  plummerterrier('Plummer Terrier'),
  podencoandaluz('Podenco Andaluz'),
  podencocanario('Podenco Canario'),
  podencovalenciano('Podenco Valenciano'),
  pointer('Pointer'),
  poitevin('Poitevin'),
  polishgreyhound('Polish Greyhound'),
  polishhound('Polish Hound'),
  polishlowlandsheepdog('Polish Lowland Sheepdog'),
  pomchi('Pomchi'),
  pomeranian('Pomeranian'),
  pontaudemerspaniel('Pont-Audemer Spaniel'),
  poochon('Poochon'),
  poodle('Poodle'),
  porcelaine('Porcelaine'),
  portuguesepodengo('Portuguese Podengo'),
  portuguesepointer('Portuguese Pointer'),
  portuguesesheepdog('Portuguese Sheepdog'),
  portuguesewaterdog('Portuguese Water Dog'),
  posavachound('Posavac Hound'),
  prazskykrysarik('Pražský Krysařík'),
  presacanario('Presa Canario'),
  pudelpointer('Pudelpointer'),
  pug('Pug'),
  puggle('Puggle'),
  puli('Puli'),
  pumi('Pumi'),
  pungsan('Pungsan'),
  pyreneanmastiff('Pyrenean Mastiff'),
  pyreneanmountaindog('Pyrenean Mountain Dog'),
  pyreneansheepdog('Pyrenean Sheepdog'),
  rafeirodoalentejo('Rafeiro do Alentejo'),
  rajapalayam('Rajapalayam'),
  rampurgreyhound('Rampur Greyhound'),
  rastreadorbrasileiro('Rastreador Brasileiro'),
  ratterrier('Rat Terrier'),
  ratonerobodegueroandaluz('Ratonero Bodeguero Andaluz'),
  ratoneromurciano('Ratonero Murciano'),
  redbonecoonhound('Redbone Coonhound'),
  rhodesianridgeback('Rhodesian Ridgeback'),
  rizekoyun('Rize Koyun'),
  romanianmioriticshepherddog('Romanian Mioritic Shepherd Dog'),
  romanianravenshepherddog('Romanian Raven Shepherd Dog'),
  rottweiler('Rottweiler'),
  roughcollie('Rough Collie'),
  russianspaniel('Russian Spaniel'),
  russkiytoy('Russkiy Toy'),
  russoeuropeanlaika('Russo-European Laika'),
  ryukyu('Ryukyu'),
  saarlooswolfdog('Saarloos wolfdog'),
  sabuesoespanol('Sabueso Español'),
  saintmiguelcattledog('Saint Miguel Cattle Dog'),
  saintusugespaniel('Saint-Usuge Spaniel'),
  sakhalinhusky('Sakhalin Husky'),
  saluki('Saluki'),
  samoyed('Samoyed'),
  sapsali('Sapsali'),
  sarabi('Sarabi'),
  sardinianshepherddog('Sardinian Shepherd Dog'),
  aarplaninac('Šarplaninac'),
  schapendoes('Schapendoes'),
  schillerstovare('Schillerstövare'),
  schipperke('Schipperke'),
  schnoodle('Schnoodle'),
  schweizerlaufhund('Schweizer Laufhund'),
  schweizerischerniederlaufhund('Schweizerischer Niederlaufhund'),
  scottishdeerhound('Scottish Deerhound'),
  scottishterrier('Scottish Terrier'),
  sealyhamterrier('Sealyham Terrier'),
  segugioitaliano('Segugio Italiano'),
  segugiomaremmano('Segugio Maremmano'),
  segugiodellappennino('Segugio dell\'Appennino'),
  serbianhound('Serbian Hound'),
  serbiantricolourhound('Serbian Tricolour Hound'),
  serranobulldog('Serrano Bulldog'),
  sharpei('Shar Pei'),
  sheepadoodle('Sheepadoodle'),
  shetlandsheepdog('Shetland Sheepdog'),
  shibainu('Shiba Inu'),
  shihtzu('Shih Tzu'),
  shihpoo('Shih-poo'),
  shikoku('Shikoku'),
  shilohshepherd('Shiloh Shepherd'),
  siberianhusky('Siberian Husky'),
  silkenwindhound('Silken Windhound'),
  sinhalahound('Sinhala Hound'),
  skyeterrier('Skye Terrier'),
  sloughi('Sloughi'),
  slovakcuvac('Slovak Cuvac'),
  slovakroughhairedpointer('Slovak Rough-haired Pointer'),
  slovenskykopov('Slovenský kopov'),
  smalandhound('Smaland Hound'),
  smallmunsterlander('Small Münsterländer'),
  smithfield('Smithfield'),
  smoothcollie('Smooth Collie'),
  smoothfoxterrier('Smooth Fox Terrier'),
  softcoatedwheatenterrier('Soft-coated Wheaten Terrier'),
  southrussianovcharka('South Russian Ovcharka'),
  spanishmastiff('Spanish Mastiff'),
  spanishwaterdog('Spanish Water Dog'),
  spinodegliiblei('Spino degli Iblei'),
  spinoneitaliano('Spinone Italiano'),
  sportinglucasterrier('Sporting Lucas Terrier'),
  springador('Springador'),
  stbernard('St. Bernard'),
  sthubertjurahound('St. Hubert Jura Hound'),
  stabyhoun('Stabyhoun'),
  staffordshirebullterrier('Staffordshire Bull Terrier'),
  standardschnauzer('Standard Schnauzer'),
  stephensstock('Stephens Stock'),
  styriancoarsehairedhound('Styrian Coarse-haired Hound'),
  sussexspaniel('Sussex Spaniel'),
  swedishlapphund('Swedish Lapphund'),
  swedishvallhund('Swedish Vallhund'),
  taigan('Taigan'),
  taiwandog('Taiwan Dog'),
  tamaskandog('Tamaskan Dog'),
  tangdog('Tang Dog'),
  tarsuscatalburun('Tarsus çatalburun'),
  tatrashepherddog('Tatra Shepherd Dog'),
  tazy('Tazy'),
  teddyrooseveltterrier('Teddy Roosevelt Terrier'),
  telomian('Telomian'),
  tenterfieldterrier('Tenterfield Terrier'),
  texasheeler('Texas Heeler'),
  thaibangkaewdog('Thai Bangkaew Dog'),
  thairidgeback('Thai Ridgeback'),
  tibetankyiapso('Tibetan Kyi Apso'),
  tibetanmastiff('Tibetan Mastiff'),
  tibetanterrier('Tibetan Terrier'),
  tibetanspaniel('Tibetan spaniel'),
  tonyafinosu('Tonya Finosu'),
  tornjak('Tornjak'),
  tosa('Tosa'),
  toyfoxterrier('Toy Fox Terrier'),
  toymanchesterterrier('Toy Manchester Terrier'),
  transylvanianhound('Transylvanian Hound'),
  treeingcur('Treeing Cur'),
  treeingfeist('Treeing Feist'),
  treeingtennesseebrindle('Treeing Tennessee Brindle'),
  treeingwalkercoonhound('Treeing Walker Coonhound'),
  trigghound('Trigg Hound'),
  tyroleanhound('Tyrolean Hound'),
  valencianterrier('Valencian Terrier'),
  vikhan('Vikhan'),
  villanodelasencartaciones('Villano de Las Encartaciones'),
  villanucodelasencartaciones('Villanuco de Las Encartaciones'),
  vizsla('Vizsla'),
  volkosob('Volkosob'),
  volpinoitaliano('Volpino Italiano'),
  weimaraner('Weimaraner'),
  welshhound('Welsh Hound'),
  welshsheepdog('Welsh Sheepdog'),
  welshspringerspaniel('Welsh Springer Spaniel'),
  welshterrier('Welsh Terrier'),
  westcountryharrier('West Country Harrier'),
  westhighlandwhiteterrier('West Highland White Terrier'),
  westsiberianlaika('West Siberian Laika'),
  westiepoo('Westiepoo'),
  westphaliandachsbracke('Westphalian Dachsbracke'),
  wetterhoun('Wetterhoun'),
  whippet('Whippet'),
  whiteshepherd('White Shepherd'),
  whiteswissshepherddog('White Swiss Shepherd Dog'),
  wirefoxterrier('Wire Fox Terrier'),
  wirehairedpointinggriffon('Wirehaired Pointing Griffon'),
  wirehairedvizsla('Wirehaired Vizsla'),
  xiasidog('Xiasi Dog'),
  xoloitzcuintle('Xoloitzcuintle'),
  yakutianlaika('Yakutian Laika'),
  yorkiepoo('Yorkiepoo'),
  yorkshireterrier('Yorkshire Terrier'),
  zerdava('Zerdava'),
  zuchon('Zuchon');

  const DogBreed(this.breed);
  final String breed;
}
